STARTING_DECK_SIZE = 13
STARTING_HP = 50
STARTING_ENERGY = 3
HP_FUZZ_MULTIPLIER = .07
BASE_HAND_SIZE = 6
BASE_DRAW_AMOUNT = 6
NUM_STAGES = 10 # for now
BASIC_AOE_DROP_CHANCE = .2 # for now
BASE_HEAL_AMOUNT = 8
HEAL_FUZZ_MULTIPLIER = .4

